[package]
name = "affirmative"
version = "0.1.1"
edition = "2021"
license = "GPL-3.0-only"
readme = "README.md"
repository = "https://github.com/centaurii44/affirmative"
description = """
Prints the specified string until interrupted.
"""

[dependencies]
